;;; En tete pour script de test ;;;;;;;;;;
; TEST_RETURN_CODE=PASS
; TEST_COMMENT=Tests conversion function between number and string
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;(number->string _)
(number->string 1)
(number->string -22)
(number->string 33.33)
(number->string +inf)
(number->string -inf)
(number->string NaN)
(number->string 1+2j)
(number->string 1.72-3j)
(char? (integer->char 97))
(+ (char->integer #\D) (char->integer #\d))
(define x (char->integer #\E))
(define y x)
(- (* 2 x) y y)
(- x y)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;(string->number _)
(string->number "123")
(string->number "12.3")
(string->number "-123")
(string->number "-inf")
(string->number "+inf")
(string->number "1+2j")
(number? (string->number "123"))
(number? (string->number "12.3"))
(number? (string->number "-inf"))
(number? (string->number "+inf"))
(number? (string->number "-123"))
(number? (string->number "1+2j"))
(+ (string->number "100") (string->number "-100"))
(+ (string->number "+inf") (string->number "-inf"))
(+ (string->number "1+2j") (string->number "10.2"))
